### ISSUE TITLE
Background image is huge

### ISSUE THREAD

**Issue by lieuwex** [Vogeltak/movemycrap-business-page#1]
It's almost 5MB and took almost 25 seconds to load
![](http://i.imgur.com/YcQTePc.png)

**Comment by Vogeltak** [comment]
Hehe, yeah, got a large picture to load. Still have to solve this, but didn't have enough time today..

On 23 August 2015 00:00:46 CEST, Lieuwe Rooijakkers <notifications@github.com> wrote:
>It's almost 5MB and took almost 25 seconds to load
>![](http://i.imgur.com/YcQTePc.png)
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/Vogeltak/movemycrap-business-page/issues/1

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
